parameters:
    form_input_types:
        text: "Sergsxm\\UIBundle\\FormInputTypes\\Text"
        textarea: "Sergsxm\\UIBundle\\FormInputTypes\\TextArea"
        html: "Sergsxm\\UIBundle\\FormInputTypes\\Html"
        password: "Sergsxm\\UIBundle\\FormInputTypes\\Password"
        checkbox: "Sergsxm\\UIBundle\\FormInputTypes\\Checkbox"
        select: "Sergsxm\\UIBundle\\FormInputTypes\\Select"
        timestamp: "Sergsxm\\UIBundle\\FormInputTypes\\TimeStamp"
        file: "Sergsxm\\UIBundle\\FormInputTypes\\File"
        number: "Sergsxm\\UIBundle\\FormInputTypes\\Number"
        image: "Sergsxm\\UIBundle\\FormInputTypes\\Image"
        address: "Sergsxm\\UIBundle\\FormInputTypes\\Address"
        tag: "Sergsxm\\UIBundle\\FormInputTypes\\Tag"
        category: "Sergsxm\\UIBundle\\FormInputTypes\\Category"

    captcha_types:
        standart: "Sergsxm\\UIBundle\\CaptchaTypes\\Standart"

    table_list_columns:
        text: "Sergsxm\\UIBundle\\TableListColumns\\Text"
        checkbox: "Sergsxm\\UIBundle\\TableListColumns\\Checkbox"
        select: "Sergsxm\\UIBundle\\TableListColumns\\Select"
        timestamp: "Sergsxm\\UIBundle\\TableListColumns\\TimeStamp"
        file: "Sergsxm\\UIBundle\\TableListColumns\\File"
        number: "Sergsxm\\UIBundle\\TableListColumns\\Number"
        image: "Sergsxm\\UIBundle\\TableListColumns\\Image"
        tag: "Sergsxm\\UIBundle\\TableListColumns\\Tag"
        category: "Sergsxm\\UIBundle\\TableListColumns\\Category"
        
services:
    sergsxm.ui:
        class: Sergsxm\UIBundle\Services\UIService
        arguments: ["@service_container", "%form_input_types%", "%captcha_types%", "%table_list_columns%"]
